spring:
  application:
    name: iam_service

  datasource:
    url: jdbc:postgresql://localhost:5432/post_hub_local
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate:
        default_schema: v1_iam_service
    database-platform: org.hibernate.dialect.PostgreSQLDialect

    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
    locations: classpath:db/migration
    schemas: v1_iam_service


server:
  servlet:
    context-path: /

  port: 8109



logging:
  level:
    root: info
    org.springframework.web: debug
    org.flywaydb: debug
